### ISSUE TITLE
Icon request: 

### ISSUE THREAD

**Issue by seguinj** [somepaulo/MoreWaita#76] opened 2023-06-26 16:03 UTC
### Name of app

Colored folders

### Link to official icon

N/A

### Optional image of the app icon

![folder-color example in Nautilus](https://github.com/somepaulo/MoreWaita/assets/2645459/507e6692-3b69-42a0-87aa-81cd3f5be4a3)

Example of folder-color in Nautilus showing the possible color variations.

** More info on how to install folder-color here: https://www.omgubuntu.co.uk/2022/11/folder-color-ubuntu-22-10-gnome-43-support

### Additional context

I think it would be a great addition if various common folder colors would be available in the icon set. This would allow users to change folder colors in Nautilus via the context menu > properties or via a tool such as folder-color.

I currently use Papirus icons for this reason only, but prefer Adwaita.

This is also possible in KDE and colored folders are part of the Breeze icon theme as well.

**Comment by dusansimic** [comment] 2023-07-30 00:06
Duplicate of https://github.com/somepaulo/MoreWaita/issues/39. Currently there are no plans to support colored folders.

**Closed by dusansimic** 2023-07-30 00:06 UTC
Labels: enhancement
