### ISSUE TITLE
VLC icon not change to light icon in dark mode

### ISSUE THREAD

**Issue by Anifyuli** [somepaulo/MoreWaita#30] opened 2023-01-09 13:49 UTC
Hello, Mister.
I found a bug on VLC tray icon. You can see in this screenshot
![Screenshot from 2023-01-08 18-52-16](https://user-images.githubusercontent.com/73734843/211323004-a8b66135-4db1-4270-b1b0-5d7cc8ff5d0a.png)
Thanks for yout attention

**Comment by somepaulo** [comment] 2023-01-12 02:43
MoreWaita, like Adwaita, does not have a light and dark icon theme variant. Moreover, the panel is always dark in GNOME Shell, so the icons are always displayed white (despite being dark by themselves), so this is not an issue with GNOME Shell, Adwaita, or MoreWaita for that matter. It has to do with either the theme or AppIndicator extension you're using.

Please, only report issues after checking against vanilla GNOME Shell with default themes. Any third-party themeing can break all sorts of things, including icons.

Cannot reproduce. Closing.

**Closed by somepaulo** 2023-01-12 02:43 UTC
